services:
  fl-client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: fl_${CLIENT_ID:?ERROR: Please run ./start_client.sh instead of docker-compose directly!}
    environment:
      - CLIENT_ID=${CLIENT_ID:?ERROR: You must provide a CLIENT_ID}
      - SERVER_IP=${SERVER_IP:?ERROR: You must provide the SERVER_IP}
      - CRYPTO_STACK=${CRYPTO_STACK:?ERROR: You must provide a CRYPTO_STACK}
    command: ["sh", "-c", "python main_client.py --id $${CLIENT_ID} --ip $${SERVER_IP} --stack $${CRYPTO_STACK}"]
    restart: on-failure
